#ifndef APEXPDF_VERSION_H
#define APEXPDF_VERSION_H

#define APX_SDK_VERSION_MAJOR 0
#define APX_SDK_VERSION_MINOR 1
#define APX_SDK_VERSION_PATCH 0
#define APX_ABI_VERSION_MAJOR 1
#define APX_ABI_VERSION_MINOR 0

#endif
